name: CI
on: push
jobs:
  test-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Playwright Browsers
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium chrome
      - name: Run e2e tests
        run: npm run test:headless
  test-macos:
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/Library/Caches/ms-playwright
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Playwright Browsers
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium chrome
      - name: Run e2e tests
        run: npm run test:headless
  test-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            %USERPROFILE%\AppData\Local\ms-playwright
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Playwright browsers and browser deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium chrome
      - name: Install Playwright browser deps
        run: npx playwright install-deps chromium chrome
      - name: Run e2e tests
        run: npm run test:headless
